<?php

/**
 * WowMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WowMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WowMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WowMenu');
    }
}